version: "3"

includes:
  tools:
    taskfile: tools/Taskfile.yaml
    dir: tools

vars:
  GOIMPORTS_REVISER_COMPANY_PREFIXES: ""

  GO_SRC_DIR: .
  GO_TOOLS_FILE: tools/tools.go
  GO_ENTRY_POINT: cmd/human-data-enricher

tasks:
  # ---------------------------------------------------------------------------- #
  #                                    Actions                                   #
  # ---------------------------------------------------------------------------- #

  # ----------------------------------- lint ----------------------------------- #
  lint:
    desc: "Lint and format source code"
    aliases: ["l"]
    vars:
      SRC_DIR: '{{default "." .GO_SRC_DIR}}'
      COMPANY_PREFIXES: '{{default "" .GOIMPORTS_REVISER_COMPANY_PREFIXES}}'
    cmd:
      task: _lint
      vars:
        SRC_DIR: "{{.SRC_DIR}}"
        COMPANY_PREFIXES: "{{.COMPANY_PREFIXES}}"
        DOCKERFILE: "{{.CONTAINER_FILE}}"
  # ---------------------------------------------------------------------------- #
  #                                  Lint action                                 #
  # ---------------------------------------------------------------------------- #
  lint:golangci:
    internal: true
    requires:
      vars: ["SRC_DIR"]
    dir: "{{.SRC_DIR}}"
    cmd: golangci-lint run

  lint:goimports-reviser:
    internal: true
    requires:
      vars: ["SRC_DIR", "COMPANY_PREFIXES"]
    cmd: GO_SRC_PATH={{.SRC_DIR}} COMPANY_PREFIXES={{.COMPANY_PREFIXES}} ./script/goimports-reviser.sh

  lint:gofumpt:
    internal: true
    requires:
      vars: ["SRC_DIR"]
    cmd: gofumpt -l -w -extra {{.SRC_DIR}}

  lint:golines:
    internal: true
    requires:
      vars: ["SRC_DIR"]
    cmd: SRC_PATH={{.SRC_DIR}} ./script/golines.sh

  lint:go-vet:
    internal: true
    requires:
      vars: ["SRC_DIR"]
    cmd: go vet {{.SRC_DIR}}/...

  __lint:
    internal: true
    requires:
      vars: ["SRC_DIR", "COMPANY_PREFIXES", "DOCKERFILE"]
    deps:
      - task: "lint:golangci"
        vars:
          SRC_DIR: "{{.SRC_DIR}}"
      - task: "lint:goimports-reviser"
        vars:
          SRC_DIR: "{{.SRC_DIR}}"
          COMPANY_PREFIXES: "{{.COMPANY_PREFIXES}}"
      - task: "lint:gofumpt"
        vars:
          SRC_DIR: "{{.SRC_DIR}}"
      - task: "lint:go-vet"
        vars:
          SRC_DIR: "{{.SRC_DIR}}"
      - task: "lint:golines"
        vars:
          SRC_DIR: "{{.SRC_DIR}}"

  _lint:
    internal: true
    requires:
      vars: ["SRC_DIR", "COMPANY_PREFIXES", "DOCKERFILE"]
    sources:
      - "{{.SRC_DIR}}/**/*.go"
    cmd:
      task: __lint
      vars:
        SRC_DIR: "{{.SRC_DIR}}"
        COMPANY_PREFIXES: "{{.COMPANY_PREFIXES}}"
        DOCKERFILE: "{{.DOCKERFILE}}"

  build:
    vars:
      ENTRY_POINT: '{{default "." .GO_ENTRY_POINT}}'
    cmd: go build -v -o main ./{{.ENTRY_POINT}}

  test:unit:
    vars:
      ENTRY_POINT: '{{default "." .GO_ENTRY_POINT}}'
    cmd: go test ./... -count=1 -v -short

  test:all:
    vars:
      ENTRY_POINT: '{{default "." .GO_ENTRY_POINT}}'
    cmd: go test ./... -count=1 -v
