version: "3"

env:
  HOST: localhost
  PORT: 5432

  USER: migrator
  PASSWORD: PASS

  DB_NAME: human-data-enricher
  SCHEMA_NAME: human-data-enricher

tasks:
  migrate:up:
    cmd: >
      migrate
      -path .
      -database "postgresql://{{.USER}}:{{.PASSWORD}}@{{.HOST}}:{{.PORT}}/{{.DB_NAME}}?sslmode=disable&options=--search_path={{.SCHEMA_NAME}}"
      -verbose up
      {{.CLI_ARGS}}

  migrate:down:
    cmd: >
      migrate
      -path .
      -database "postgresql://{{.USER}}:{{.PASSWORD}}@{{.HOST}}:{{.PORT}}/{{.DB_NAME}}?sslmode=disable&options=--search_path={{.SCHEMA_NAME}}"
      -verbose down
      {{.CLI_ARGS}}

  migrate:fix:
    cmd: >
      migrate
      -path .
      -database "postgresql://{{.USER}}:{{.PASSWORD}}@{{.HOST}}:{{.PORT}}/{{.DB_NAME}}?sslmode=disable&options=--search_path={{.SCHEMA_NAME}}" force
      {{.CLI_ARGS}}
